<a href="https://colab.research.google.com/github/yesung05/2024-intro-DA-code/blob/main/w04_5_python_nparray_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SECTION 5 배열 슬라이싱과 형태 수정

## 1차원 배열의 첨자와 슬라이싱

In [3]:
import numpy as np

a = np.power(np.arange(10),2) # 2 제곱씩
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
print(a[3])
print(a[-2]) #기존 리스트 슬라이싱이랑 거의 비슷
#  0  1  2  3  4  5
# -6 -5 -4 -3 -2 -1

9
64


In [7]:
print(a[1:4]) #개념 똑바로 안 잡아두면 많이 햇갈릴 수 있는 부분, 1부터 4전(3)까지
print(a[-5:-1]) #이렇게 2 개로만 슬라이싱 할 때 start 가 end 보다 오른쪽에 있으면 아무겄도 안 나왔었나
# print(a[4:1]) 맞네

[1 4 9]
[25 36 49 64]


In [9]:
print(a[8:2:-1]) #아 이건 뒤집어서 적은 후 -1 해야하는구나..
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [15]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [18]:
a[::-2] #책에서는 dtype이 같이 출력 되었는데 안 나오는 이유를 찾아보니 버전 차이같다고 한다.

array([81, 49, 25,  9,  1])

In [20]:
a[2:5] = -100
a #이렇게 한번에 수정 가능

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [21]:
a[2:5] =  [-5,-5,-5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [23]:
a[2:5] = [-5,-5] #슬라이싱 된 부분보다 더 작거나 많은 데이터 대입 X

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [32]:
b = np.array([5]*10)
b
# np.full(10,5) 같은거.. 나 이거 시험에 나오면 1학기 중간처럼 fill 쓸수도..

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [34]:
b[::2] = -10 #2칸식 건너 뛰면서 그 장소에 -10 넣기
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [35]:
b[::2] = np.arange(5) #[0,1,2,3,4,5] 를 2칸씩 건너 뛰면서 그 장소에 넣기
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

## 2차원 배열의 첨자와 슬라이싱

In [37]:
a = np.arange(30).reshape(5,6) #1~30 배열을 5x6으로 배열로 재구성
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [39]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [40]:
a[-2,:] # 두번째 : 생략 가능

array([18, 19, 20, 21, 22, 23])

In [41]:
a[2:4] # 사실 2차원 배열/리스트 등은 개념 이해하면 그닥 어렵지는 않은데 햇갈리는거 조심

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [42]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [52]:
a[:,1] #모든 행에 첫 데이터
# a[:][1] #이건 또 결과가 다르네?

array([ 1,  7, 13, 19, 25])

In [64]:
a[:,1:6] #리스트는 이런거 안되네 뭔가 개념이 살짝 다른듯

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [65]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [66]:
a[2,4] #해당 위치에 있는 하나의 데이터만 가져오기

16

In [67]:
a[2][4]#이건 리스트랑 같음

16

In [68]:
a[1:3,2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [70]:
a[:,:] #그냥 다 출력

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [72]:
a[::-1,::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

## 3차원 배열의 첨자와 슬라이싱

In [74]:
a = np.arange(24).reshape(2,3,4)
a
#3차원 배열은 0층에 2차원 배열 하나, 1층에 2차원 배열 하나 n층에 2차원 배열 하나 있다고 생각하면 편한듯

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [76]:
a[1] #1층 가져오기

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
a[:,1] #모든 층에서 1번 행 가져오기

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [79]:
a[:, 1, 1] #모든 층에서 행과 열의 번호가 1인것만 가져오기

array([ 5, 17])

In [80]:
a[...,1] # == a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [81]:
a[1, ..., 1] #a[1,:,1]

array([13, 17, 21])

In [82]:
a[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 1차원 배열로 만드는 ndarray.ravel()

In [96]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [97]:
a.ravel() #이번에 배운것 중 가장 간단한듯

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## np.transpose(a) 와 a.transpose(), a.T

In [98]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
np.transpose(a) #저장은 x


array([[1, 4],
       [2, 5],
       [3, 6]])

In [100]:
a.transpose() #저장은 x

array([[1, 4],
       [2, 5],
       [3, 6]])

In [104]:
a.T #이건 괄호가 있으면 오류나네

array([[1, 4],
       [2, 5],
       [3, 6]])

In [105]:
np.transpose(a,(0,1))

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
np.transpose(a,(1,0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [107]:
b = np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [108]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [109]:
np.transpose(b,(0,1,2)) #기본 원상태

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [110]:
np. transpose(b,(2,1,0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [111]:
np.transpose(b,(0,2,1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [112]:
c = np.arange(1,13).reshape(2,2,3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [113]:
c.transpose(1,2,0)

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [114]:
np.transpose(c,(1,2,0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [115]:
np.transpose(c) #기본 변환 값

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

## np.swapaxes()

In [124]:
x = np.array([[7,8,9]]) #[]가 2세트 있으니 어찌됐건 2차원
x

array([[7, 8, 9]])

In [125]:
y = np.swapaxes(x,0,1)
y

array([[7],
       [8],
       [9]])

In [127]:
y[0,0] = 10 #y는 원본이 아니라 x를 끌어다 쓰고 있음. 그러므로 y를 수정해도 x가 같이 수정 됨
x

array([[10,  8,  9]])

In [129]:
x =  np.array(np.arange(8).reshape(2,2,2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [130]:
np.swapaxes(x,0,2) #이 부분 좀 더 공부 필요..

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [131]:
np.transpose(x,(2,1,0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

## 보기(view)

In [132]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [134]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [135]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [136]:
org

array([  0,   1, 200,   3,   4])

In [137]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [138]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [139]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [140]:
org

array([0, 1, 2, 3, 4])

## 배열이 뷰인지 복사본인지 확인하는 방법

In [141]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [142]:
y = x.reshape(2,3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [144]:
y.base #원본이 있으면 원본배열 표시

array([0, 1, 2, 3, 4, 5])

In [145]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [146]:
c = z.copy()
print(c.base)

None


## ndarray의 구조로 같은 구조만 수정 가능

In [147]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [150]:
lst[3:5] = [30,40,50] #2개 슬라이싱에 3개 추가
lst

[0, 1, 2, 30, 40, 50, 50, 50, 5, 6, 7]

In [151]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [153]:
x[3:5] = [30,40] #이건 리스트랑 배열 둘다 문제 X
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [154]:
x[3:5] = [30,40,50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

## 얕은 복사(shallow copy)

In [155]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [156]:
b = a #리스트도 이런거 있는데 []하면 깊은 복사고
b is a

True

In [157]:
print(id(a))
print(id(b))

136840961450672
136840961450672


In [158]:
print(b.base)

None


In [159]:
b[0,0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [160]:
v = a.reshape(3,2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [161]:
print(id(a))
print(id(v))

136840961450672
136840961372688


In [163]:
v[0,1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [164]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])