<a href="https://colab.research.google.com/github/yesung05/2024-intro-DA-code/blob/main/w04_2_python_numpy_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SECTION 02 내장함수 arange()와 linspace()

## numpy의 내장함수 arange()개요

In [2]:
import numpy

In [6]:
help(numpy.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

## 내장함수 arange() 활용

In [9]:
import numpy as np
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2)) #배열 생성 인자부분 비워놓고 채우라 하기, 인자 부분 보고 배열 만들라 하기?
#리스트와 다르게 쉼표 없음!
# 이 중에서 ndarray를 고르시오. 시험에 나올까..?
#1. {1,2,3} 2. (1,2,3) 3.[1 2 3] 4.[1,2,3]

[0 1 2]
[3 4 5 6]
[3 5]


In [14]:
import numpy as np

print(np.arange(2.0)) # 그냥 range와 다르게 실수 사용 가능
print(np.arange(2.0,6.5))
print(np.arange(2.0,6.5,0.8)) # 예도 6.5 전까지임. step을 0.5로 해도 6.5 출력 안됨

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


## 배열의 모양을 바꾸는 reshape()

In [16]:
import numpy as np #아까 이미 작성해서 필요 없긴 한데..

a = np.arange(12).reshape(3, 4) #1~12전 까지 있는 1차원 배열 생성과 동시에 행3 열4의 배열로 변경
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
np.reshape(a,(2,6)) #이부분 교제 잘못됨

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [18]:
np.reshape(a,(3,5)) #기존 배열인 12칸 의 범위를 벗어나서 오류

ValueError: cannot reshape array of size 12 into shape (3,5)

In [19]:
np.reshape(a,(2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [23]:
b = np.array([1,2,3,4,5,6]).reshape(3,2)
b
# print(b) #이걸로 출력하면 ',' 없음

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
np.reshape(b, (2,-1)) #음 자동생성.. 파이썬은 정말 별의 별 기능이 다 있다니까

array([[1, 2, 3],
       [4, 5, 6]])

## 일정한 간격의 값으로 배열을 만드는 linspace()

In [29]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, s

In [31]:
import numpy as np

np.linspace(2.0,3.0) # 교수님 중간고사 O, X 문제중 linspace 함수의 기본 값은 50개이다 (O, X) 나올 가능성 있음.
#linspace는 햇갈리게 stop까지 기본으로 같이 출력함;

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [49]:
np.linspace(2.0,3.0,retstep=True) #
# np.linspace(2.0,3.0,retstep=1)
# testi = 2.0
# for i in range(50):
#     print(testi)
#     testi+=0.02040816326530612
# 이 경우는 2.9999999등등으로 끝나네 이게 부동 소수점 오차 그건가

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [44]:
print((3-2)/(50-1)) #(끝 - 시작) / (분할 개수-1) 시작과 끝의 차이를 분할 개수-1개로 나눔 (시작값과 끝값은 그냥 출력해서?) 걍 쉬우니까 외우자.

0.02040816326530612


In [47]:
np.linspace(2.0,3.0,endpoint=False, retstep=True) #그러고 보니까 예는 end stop 이라 괄호 없구나

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 0.02)

In [48]:
print((3-2)/50)

0.02


In [51]:
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [55]:
np.linspace(2.0,3.0,num=5,endpoint=False,retstep=False) #파이썬 함수 동작원리상 인자 위치만 맞으면 'num=' 없어도 원하는 작동을 하지만 햇갈리니까 이렇게 쓰자.

SyntaxError: positional argument follows keyword argument (<ipython-input-55-eee948a4b4f1>, line 1)

##내장함수 arange() 와 linspace()비교

In [56]:
np.arange(0.1,0.4,0.1) #0.1에서 0.4까지 0.1씩 증가

array([0.1, 0.2, 0.3, 0.4])

In [57]:
np.arange(1,4,1) /10.0 #1,2,3을 10으로 나누어서

array([0.1, 0.2, 0.3])

In [58]:
np.linspace(0.1, 0.4, 3, endpoint= False)

array([0.1, 0.2, 0.3])

In [59]:
np.linspace(0.1,0.4,4)

array([0.1, 0.2, 0.3, 0.4])