<a href="https://colab.research.google.com/github/yesung05/2024-intro-DA-code/blob/main/w04_1_python_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SECTION 01 패키지 numpy 개요와 자료형 ndnarra

## 다차원 배열 ndarray

In [1]:
import numpy as np

a = np.ndarray(shape=(2,2),dtype=int)
a

array([[99231491512607,              0],
       [99254628514440,              0]])

## 내장함수 array()로 ndarray 생성

In [2]:
import numpy as np

a = np.array([1,2,3],dtype=int) #배열 안에 값으로 ndarray 생성?
a

array([1, 2, 3])

In [3]:
print(a.shape) # ndarray 속성 보기 (모양)
print(a.ndim) # ndarray 속성 보기(차원)
print(a.dtype) # ndarray 속성 보기(데이터 타입)

(3,)
1
int64


In [4]:
import numpy as np

np.array(1,2,3) #괄호 필수!!!!!! 이거 시험에 틀린거 고르라고 나올 가능성 좀 있을듯.

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [8]:
np.array([1,'py',3.14]) #정수, 실수->실수 정수, 실수, 문자열-> 문자열
# np.array((1,2,3)) 예는 출력에 dtype 안나오네..?

array(['1', 'py', '3.14'], dtype='<U32')

In [9]:
import numpy as np

unicode_array = np.array(['가나다','라마바','사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [10]:
lang = np.array(['파이썬','자바','씨']) #왜 혼합되면 U32자동 적용이고 그냥 한글만 하면 U3이지?
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [11]:
a = np.array((1,2,3), dtype=float)
a

array([1., 2., 3.])

In [12]:
b = np.array((1,2.5,3))
b

array([1. , 2.5, 3. ])