<a href="https://colab.research.google.com/github/yesung05/2024-intro-DA-code/blob/main/w04_4_nparray_calculate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SECTION 4 배열 연산

## 배열과 스칼라의 연산

In [4]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [6]:
print(a+2) #모든 값에 2씩 더하기
print(a-2) #모든 값에 2씩 빼기
print(a*2) #모든 값을 2로 곱하기
print(a/2) #모든 값을 2로 나누기

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [7]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b = np.full_like(a,[1,2,3]) # a 와 같은 배열구조에 1,2,3 이 들어간 배열 생성

In [13]:
print(a+b) #1+1 2+2 3+3 4+1 5+2 6+3 등등
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [24]:
a= np.arange(4)
a

array([0, 1, 2, 3])

In [17]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [25]:
a += b #a는 int 형인데 int형+실수 더해서 나온 실수 결과를 a 에 넣을려 해서 오류 발생
# 근데 a 왜 int지 햇갈리게..

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [27]:
b+=a #실수는 정수를 담을 수 있음
b

array([0.5, 3.5, 6.5, 9.5])

In [28]:
a = np.full((2,3),[1,2,3])
a #a의 열과 b의 행이 같아야 함

array([[1, 2, 3],
       [1, 2, 3]])

In [30]:
b = np.full((3,2),[2,1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [31]:
a @ b

array([[12,  6],
       [12,  6]])

In [33]:
a.dot(b) #같은거

array([[12,  6],
       [12,  6]])

In [34]:
b.dot(a) #반대로 되는 이유는 a와 b의 행과 열, 열과 행이 서로 같기떄문

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

## 배열 함수

In [36]:
a = np.array([[10,20],[5,6],[1,2]]) #2차원
a

array([[10, 20],
       [ 5,  6],
       [ 1,  2]])

In [37]:
a.sum()

44

In [39]:
a.sum(axis=0) #0은 세로끼리 1은 가로끼리

array([16, 28])

In [40]:
a.sum(axis=1)

array([30, 11,  3])

In [43]:
import numpy as np
#sum 자체는 기본으로 있는데 np.sum은 기능이 다른가?
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

44
[16 28]
[30 11  3]


In [44]:
## 중간고사 시험!!!! ! ! !! ! !
a = np.array([[3,5,7],[1,2,3]])
a

array([[3, 5, 7],
       [1, 2, 3]])

In [46]:
a.cumsum() #배열의 값을 지속적으로 더함

array([ 3,  8, 15, 16, 18, 21])

In [47]:
a.cumsum(axis=0)

array([[ 3,  5,  7],
       [ 4,  7, 10]])

In [48]:
a.cumsum(axis=1)

array([[ 3,  8, 15],
       [ 1,  3,  6]])

## 범용 함수

In [49]:
import numpy as np
a = np.array([1,4,9])
np.sqrt(a) #제곱해서 n이 되는 것

array([1., 2., 3.])

In [50]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [52]:
import numpy as np

a = np.array([1,4,9])
a

array([1, 4, 9])

In [53]:
b = np.full_like(a,2)
b

array([2, 2, 2])

In [54]:
np.add(a,b)

array([ 3,  6, 11])

In [56]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [57]:
np.power(a,b)

array([ 1, 16, 81])