<a href="https://colab.research.google.com/github/yesung05/2024-intro-DA-code/blob/main/w05_2_numpy_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SECTION 07 고급 색인

##  1차원 배열의 색인

In [3]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [6]:
print(x[[2]])
print(x[[2,3]])

[2]
[2 3]


In [7]:
x[[2,3,5,8]]

array([2, 3, 5, 8])

In [9]:
x[np.array([5,3,-4,-8])]

array([5, 3, 6, 2])

In [10]:
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

## 2차원 배열의 색인

In [12]:
from numpy import arange

x = arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [13]:
x[0,1]

1

In [14]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [15]:
x[[0],[1]]

array([1])

In [16]:
x[:, [5,4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [17]:
x[[1,3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [18]:
x[[1,3],:]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [19]:
x[[1,3],[2,2]]

array([10, 26])

In [20]:
x[[1,3],[2]]

array([10, 26])

In [21]:
x[[1,3],[3,3]]

array([11, 27])

In [22]:
x[[1, 3], [3]]

array([11, 27])

In [24]:
from numpy import array
x[array([0,2,4]), array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [25]:
x[np.array([0,2,4]),1]

array([ 1, 17, 33])

In [26]:
print(x[0,1])
print(x[2,1])
print(x[4,1])

1
17
33


## 기본 색인 방법

In [27]:
from numpy import arange

a = arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [28]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

## 고급 색인 방법

In [29]:
a[arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [30]:
a[arange(2,4)][:,[1,0]]

array([[17, 16],
       [25, 24]])

In [31]:
a[arange(2,5)][:,[1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [32]:
a[arange(2,5)][:,arange(-1,-8,-1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])