<a href="https://colab.research.google.com/github/yesung05/2024-intro-DA-code/blob/main/w05_1_numpy_application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SECTION 06 브로드캐스팅

In [ ]:
from numpy import array

a = array([3,4,5])
b = array([8,7,6])
a+b

array([11, 11, 11])

In [ ]:
from numpy import array

a = array([3,4,5,7])
b = array([8,7,6])
a*b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

## 스칼라 또는 단일 값과 배열의 연산

In [ ]:
from numpy import array
a = array([3,4,5])
a

array([3, 4, 5])

In [ ]:
b = 2
b

2

In [ ]:
a + b

array([5, 6, 7])

In [ ]:
from numpy import array

A = array([[1,2,3],[1,2,3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
A + 2

array([[3, 4, 5],
       [3, 4, 5]])

In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
from numpy import arange

x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = arange(-1,2)
y

array([-1,  0,  1])

In [ ]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [ ]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

##  하나의 배열이 1차원으로 다른 배열 행수와 같은 구조의 브로드캐스팅

In [ ]:
from numpy import arange

x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = arange(3,10,3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [ ]:
x / y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [ ]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

## 행 또는 열이 1인 두 배열의 브로드캐스팅

In [ ]:
from numpy import arange

x = arange(1,4)

In [ ]:
y = arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [ ]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [ ]:
x-y

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [ ]:
from numpy import arange

x = arange(0,10,3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [ ]:
y = arange(1,3)
y

array([1, 2])

In [ ]:
x*y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [ ]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

## 상수 np.newaxis 활용해 두 배열의 브로드캐스팅

In [ ]:
from numpy import array

x = array([0,10,20,30])
x

array([ 0, 10, 20, 30])

In [ ]:
a = x[None,:] #한 차원 추가
a

array([[ 0, 10, 20, 30]])

In [ ]:
a = x[np.newaxis,:]

In [ ]:
a = x[:,np.newaxis]

In [ ]:
from numpy import array

b = array([1,2,3])
b

array([1, 2, 3])

In [ ]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
a*b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])