<a href="https://colab.research.google.com/github/yesung05/2024-intro-DA-code/blob/main/w05_3_array_stack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#SECTION 01 배열 결합

## numpy.vstack()

In [ ]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a,b)) # 수직으로 쌓기

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
c = np.arange(20,24).reshape(2,2)

In [ ]:
np.vstack((a,c)) #수직으로 쌓기

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [ ]:
np.vstack((a,b,c)) #3개 한번에 쌓기

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [ ]:
d = np.array([100,200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [ ]:
d = np.array([100,200,300]) #모양 안 맞아서 오류
np.vstack((a,d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
import numpy as np

x = np.array([1,2,3])
y = np.array([4,5,6])
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

## numpy.hstack()

In [ ]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.hstack(((a,b))) #두개를 옆으로 연장

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [ ]:
c = np.array([[10,20],[30,40]])
c

array([[10, 20],
       [30, 40]])

In [ ]:
np.hstasck((a,c))

AttributeError: module 'numpy' has no attribute 'hstasck'

In [ ]:
np.hstack((np.arange(3),np.arange(10,15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

## numpy.column_stack

In [ ]:
import numpy as np
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.arange(10,22).reshape(3,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
np.column_stack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [ ]:
x = np.array([1,2,3]) #세로로 돌린 후 옆으로 쌓기
y = np.array([4,5,6])
np.column_stack((x,y))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x[:,np.newaxis] #column_stack 실행 과정 분해

array([[1],
       [2],
       [3]])

In [ ]:
y[:,np.newaxis]

array([[4],
       [5],
       [6]])

In [ ]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x[:,np.newaxis],y[:,np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.hstack((x,y))

array([ 1,  2,  3, 10, 20, 30])

In [ ]:
np.column_stack == np.hstack

False

## numpy.row_stack()

In [ ]:
import numpy as np
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b = np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
a = np.array([4.,2.,1.])
b = np.array([3.,8.,7.])
print(np.row_stack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [ ]:
print(np.vstack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [ ]:
np.row_stack == np.vstack

True

## numpy.concatenate()

In [ ]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe

In [ ]:
import numpy as np

a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b,c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np

x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z = np.arange(20,24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

In [ ]:
np.concatenate((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.concatenate((x,y,z))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 2

In [ ]:
np.concatenate((x,y,z),axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [ ]:
np.concatenate((x,y),axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

##numpy.stack()

In [3]:
import numpy as np

a = np.array([1,2,3])
a

array([1, 2, 3])

In [2]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [4]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
y = np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [8]:
z = np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

## np stack()로 배열 x,y,z를 0번 축 방향으로 합치기

In [10]:
ax0 = np.stack((x,y,z),axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [11]:
ax0.shape

(3, 2, 3)

In [12]:
ax1 = np.stack((x,y,z),axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [14]:
ax1.shape #책 오류! p158

(2, 3, 3)

In [15]:
ax2 = np.stack((x,y,z),axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [17]:
ax2.shape #이것도 책 오류.. p159

(2, 3, 3)

## np.stack(axis=2) 분해

In [18]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
x[:,:,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [20]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [21]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [22]:
y[:,:,np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [23]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [24]:
np.expand_dims(z,axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [25]:
np.stack((x,y,z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

## 배열의 결합 비교 column_stack()과 hstack()

In [26]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
c= np.arange(1,6,2)
c

array([1, 3, 5])

In [33]:
c[:,np.newaxis]

array([[1],
       [3],
       [5]])

In [29]:
np.hstack((a,c[:,np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [30]:
np.hstack((a,c)) #2차원 배열이랑 1차원 배열을 합치려 하여 에러 c[:,np.newaxis]는 출력만 형상 바꿔서 출력하는거지 변수를 수정하는것이 아님

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [34]:
np.hstack((a,np.expand_dims(c,axis=1))) # np.expand_dims(c,axis=1)은 그냥 2차원 배열의 c로 보면 됨

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [35]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

## row_stack()과 vstack()

In [44]:
np.row_stack==np.vstack #책에는 없다 row_stack과 vstack은 완전히 같은 함수이다. (O, X)

True

In [36]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [38]:
np.row_stack((a,b)) #괄호 안에 괄호 있는것은 인자값이 n개 들어가는 경우에 데이터 묶음 형태로 집어넣나봄

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [39]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

## np.c_[]와 np.column_stack()

In [45]:
help(np.c_)

Help on CClass in module numpy.lib.index_tricks object:

class CClass(AxisConcatenator)
 |  Translates slice objects to concatenation along the second axis.
 |  
 |  This is short-hand for ``np.r_['-1,2,0', index expression]``, which is
 |  useful because of its common occurrence. In particular, arrays will be
 |  stacked along their last axis after being upgraded to at least 2-D with
 |  1's post-pended to the shape (column vectors made out of 1-D arrays).
 |  
 |  See Also
 |  --------
 |  column_stack : Stack 1-D arrays as columns into a 2-D array.
 |  r_ : For more detailed documentation.
 |  
 |  Examples
 |  --------
 |  >>> np.c_[np.array([1,2,3]), np.array([4,5,6])]
 |  array([[1, 4],
 |         [2, 5],
 |         [3, 6]])
 |  >>> np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]
 |  array([[1, 2, 3, ..., 4, 5, 6]])
 |  
 |  Method resolution order:
 |      CClass
 |      AxisConcatenator
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self)
 |     

In [50]:
np.c_ == np.column_stack #책에는 없음

False

In [47]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

In [48]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
np.c_[a,b]==np.column_stack((a,b)) #책에는 없음 이렇게 하면 내용끼리 비교하는구나..

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [54]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [55]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

## np.r_[] 개요

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
np.r_[a,b]

In [56]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [57]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.r_[a,0,0,b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [59]:
np.r_[3:10:3,[0]*2,5,6]

array([3, 6, 9, 0, 0, 5, 6])

In [60]:
np.r_[-1:1:6j, [0]*2,5,6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [61]:
np.linspace(-1,1,6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

## np.r_['i, j, k', a , b]

In [62]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
np.r_[a,a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [64]:
np.r_['0',a,a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [65]:
np.r_['-1',a,a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [66]:
np.r_['1',a,a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [67]:
np.r_['0,2',[1,2,3],[4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.r_['0,3',[1,2,3],[4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [69]:
np.r_['0,3,0',[1,2,3],[4,5,6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [70]:
np.r_['0,3,0',[1,2,3],[4,5,6]].shape

(6, 1, 1)

In [71]:
np.r_['0,3,1',[1,2,3],[4,5,6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [72]:
np.r_['0,3,1',[1,2,3],[4,5,6]].shape

(2, 3, 1)

In [73]:
np.r_['0,3,2',[1,2,3],[4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

## 여러 1차원 배열을 수평 방향으로 합치는 방법

In [74]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a.shape)
print(b.shape)

(3,)
(3,)


In [75]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [76]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [78]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

## 여러 1차원 배열을 수직 방향으로 합치는 방법

In [79]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [80]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
np.r_[a[np.newaxis,:],b[np.newaxis,:]]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
np.concatenate((a[np.newaxis,:],b[np.newaxis,:]))

array([[1, 2, 3],
       [4, 5, 6]])

## 여러 1차원 배열을 행으로 확장해 수평 방향으로 합치는 방법

In [84]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [85]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
np.hstack((a[:,np.newaxis],b[:,np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [87]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [88]:
np.concatenate(((a[:,np.newaxis],b[:,np.newaxis])),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])