<a href="https://colab.research.google.com/github/yesung05/2024-intro-DA-code/blob/main/w06_nparray_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SECTION 02 배열의 분리

## 기본함수 np.split()

In [3]:
import numpy as np
help(np.split)

Help on _ArrayFunctionDispatcher in module numpy:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays as views into `ary`.
    
    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.
    
        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in
    
          - ary[:2]
          - ary[2:3]
          - ary[3:]
    
        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.
    
    Returns
    -------
    sub-arra

## np.split(ary,n)

In [ ]:
import numpy as np

x = np.arange(0,9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
s = np.split(x,3)
s

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [ ]:
print(type(s))
print(s[0])

<class 'list'>
[0 1 2]


In [ ]:
np.split(x,4) #나누어 떨어지지 않아 오류

ValueError: array split does not result in an equal division

## np.split(ary, [i,j,k,...])

In [ ]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.split(x,[2,6])

[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8, 9])]

In [ ]:
y = np.arange(10,61,10)
y

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.split(y,[2,3,4])

[array([10, 20]), array([30]), array([40]), array([50, 60])]

In [ ]:
np.split(y,[2,3,4,6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [ ]:
y[4:6]

array([50, 60])

In [ ]:
y[6:]

array([], dtype=int64)

## 다차원 배열 np.hsplit(ary, n)

In [ ]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
np.split(a,3, axis = 1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
np.split(a,4, axis = 1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [ ]:
np.split(a, 5, axis=1)

ValueError: array split does not result in an equal division

In [ ]:
np.split(a,[3,5,7],axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [ ]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.split(b,3,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [ ]:
np.split(b,[2,4,6],axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

## 분할 함수 hsplit()과 split()
### np.hsplit(ary)

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.hsplit(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
np.hsplit(a,[2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [4]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [5]:
np.hsplit(a,3) #나누어 떨어짐

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [7]:
np.hsplit(a,4) #나누어떨어짐

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [8]:
np.hsplit(a,5) #나누어 떨어지지 않음

ValueError: array split does not result in an equal division

In [9]:
np.hsplit(a,(3,5,8)) # [:, :3]  [:, 3:5] [:, 5: 8], [: 8:]

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [10]:
a[:,:3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [11]:
a[:,8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

## np.vsplit(ary)

In [12]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.vsplit(2) #vsplit은 2차원 이상에서만 가능

TypeError: vsplit() missing 1 required positional argument: 'indices_or_sections'

In [14]:
a = np.arange(18).reshape(6,3)

In [15]:
np.vsplit(a,3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [16]:
np.vsplit(a,4) #6%4 != 0

ValueError: array split does not result in an equal division

In [18]:
np.vsplit(a,(1,4,6)) #마지막 분할 잘못하면 빈 배열 출력

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [19]:
a[4:6,:]

array([[12, 13, 14],
       [15, 16, 17]])

In [20]:
a[6:, :] #빈 배열 출력

array([], shape=(0, 3), dtype=int64)